# Nombre de la app
spring.application.name= servicioAgregacion
server.port=${SERVER_PORT}

# Configuracion Sistema
app.pagination.hechos.size = 20
app.pagination.colecciones.size = 20
app.hechos.comparadores=titulo
# Cron expressions
cron.fuentes.actualizar=0 0 * * * *
cron.colecciones.actualizar=0 30 * * * *
cron.colecciones.curar=0 0 3 * * *

#Actualizacion proxy
hechos.proxy.actualizacion.duracion=PT20M

# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de sincronización de entities contra la base de datos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# jwt key
jwt.secret.base64= ${JWT_SECRET_BASE64}
