spring.application.name=Servicio Agregación
app.base-url=http://localhost:8084
puertoFuenteEstatica=8080
puertoFuenteDinamica=8081
puertoFuenteProxy=8082
puertoServicioEstadisticas=8083
puertoServicioAgregacion=8084