spring.application.name=fuenteEstatica
server.port=${SERVER_PORT}

# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Configuración JWT (validador)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.issuer-uri=servicio-usuarios

logging.level.org.springframework.security=INFO

# jwt key
jwt.secret.base64= ${JWT_SECRET_BASE64}