spring.application.name=servicioEstadisticas
server.port=8088
app.base-url=http://localhost:8088

agregador.base-url=http://localhost:8080
estadisticas.cantDiasPersistencia=30

jwt.secret.base64= E0m0k6c9fG8W6u2u3p3H3t2c6O0m3w9Q2pEmx0gA1yY

# Crons
cron.calculoEstadisticas= 0 0 6 */7 * *
cron.eliminarEstadisticas=0 0 1 * * Mon


# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/meta_mapa_estadisticas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de sincronización de entities contra la base de datos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# para ver los logs
logging.level.ar.edu.utn.frba.dds=INFO