spring.application.name=fileSystem
# Hardcodear puerto para evitar problemas con variables
server.port=${SERVER_PORT}

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=0

# Directorio hardcodeado (coincide con el volumen)
app.directorio.destino=${APP_DIRECTORIO_DESTINO}

# Logging agresivo para debug
logging.level.root=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.springframework.web=DEBUG
logging.level.ar.edu.utn.frba.dds=DEBUG

# Evitar errores de inicio
spring.main.banner-mode=off
server.error.include-message=always
server.error.include-stacktrace=always