spring.application.name=fileSystem
server.port=8091

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=0
# Ruta base del fileSystem
app.directorio.destino=C:\\Proyectos\\UTN\\DDSI\\filesystem-data