# Nombre de la app
spring.application.name= servicioAgregaci�n
server.port=8080
app.agregador-url=http://localhost:8080

# URLs de fuentes
app.fuenteEstatica-url=http://localhost:8081
app.fuenteDinamica-url=http://localhost:8082
app.fuenteProxy-url=http://localhost:8083

# Configuracion Sistema
app.pagination.hechos.size = 20
app.pagination.colecciones.size = 20
app.hechos.comparadores=categoria,titulo
# Cron expressions
cron.fuentes.actualizar=0 0 * * * *
cron.colecciones.actualizar=0 10 * * * *
cron.colecciones.curar=0 0 3 * * *

#Actualizacion proxy
hechos.proxy.actualizacion.duracion=PT20M

# Configuraci�n de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/meta_mapa_agregador?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=gonzalo1273
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuraci�n de sincronizaci�n de entities contra la base de datos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

