spring.application.name=MetaMapa
app.base-url=http://localhost:8080


api.ddsi.base-url=https://api-ddsi.disilab.ar/public
api.ddsi.token=rY3j0CD1b4hpJBNWwZvJkva2NhsGEukeS2pFQkjE2yMBmk6sdlGQ5ATQkpYo

api.metamapa.base-url=https://22e8acb1-7e59-4c25-94fb-d9892865200e.mock.pstmn.io
