spring.application.name=clienteGrafico
server.port=${SERVER_PORT}

app.hechos.page.size=20
app.colecciones.page.size=20

auth.service.url=${AUTH_SERVICE_URL}
servicio.agregador.url=${SERVICIO_AGREGADOR_URL}
fuente.estatica.url=${FUENTE_ESTATICA_URL}
fuente.dinamica.url=${FUENTE_DINAMICA_URL}
fuente.proxy.url=${FUENTE_PROXY_URL}
servicio.estadisticas.url=${SERVICIO_ESTADISTICAS_URL}
file.system.url=${FILE_SYSTEM_URL}

# Tamaño máximo por archivo
spring.servlet.multipart.max-file-size=10MB
# Tamaño máximo total de la petición
spring.servlet.multipart.max-request-size=10MB

# Configuración Datadog

## Exponer endpoints de Actuator (para health y metrics)
management.endpoints.web.exposure.include=health,info,metrics

# API key de Datadog (inyectada por env var)
management.datadog.metrics.export.api-key=${DD_API_KEY}

# Site de Datadog (porque estás en us3)
management.datadog.metrics.export.uri=https://api.us3.datadoghq.com

# Enviar métricas cada 10s
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=10s

# Tags globales para todas las métricas
management.metrics.tags.env=${DD_ENV}
management.metrics.tags.service=${spring.application.name}
management.metrics.tags.version=${DD_VERSION}

