spring.application.name=fuenteDinamica
server.port=8082
app.base-url=http://localhost:8082

# Configuracion de negocio del sistema
hecho.diasModificacion=7
hecho.diasSugerencia=7

cron.hechos.rechazarSugerencia= 0 0 0 * * *

app.pagination.hechos.size = 20


# Configuración de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de sincronización de entities contra la base de datos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# jwt key

jwt.secret.base64= ${JWT_PS}