spring.application.name=fuenteDinamica
server.port=8082
app.base-url=http://localhost:8082

# Configuracion de negocio del sistema
hecho.diasModificacion=7
app.pagination.hechos.size = 20


# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/meta_mapa_dinamica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de sincronización de entities contra la base de datos

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# jwt key

jwt.secret.base64= E0m0k6c9fG8W6u2u3p3H3t2c6O0m3w9Q2pEmx0gA1yY