spring.application.name=servicioUsuarios
server.port=${SERVER_PORT}

jwt.secret.base64= ${JWT_SECRET_BASE64}

# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuración Datadog

## Exponer endpoints de Actuator (para health y metrics)
management.endpoints.web.exposure.include=health,info,metrics

# API key de Datadog (inyectada por env var)
management.datadog.metrics.export.api-key=${DD_API_KEY}

# Site de Datadog (porque estás en us3)
management.datadog.metrics.export.uri=https://api.us3.datadoghq.com

# Enviar métricas cada 10s
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=10s

# Tags globales para todas las métricas
management.metrics.tags.env=${DD_ENV:dev}
management.metrics.tags.service=${spring.application.name}
management.metrics.tags.version=${DD_VERSION:1.0.0}