@startuml
skinparam classAttributeIconSize 0

package entities {

  enum TipoFuenteProxy {
    EXTERNA
    METAMAPA
  }

  ' ===== Interfaz base =====
  interface IFuente {
    +Long getId()
    +void setId(Long id)
    +TipoFuenteProxy getTipo()
    +void setNombre(String nombre)
    +String getBaseUrl()
  }

  ' ===== Interfaces de capacidad =====
  interface ServidoraDeHechos extends IFuente {
    +Mono<List<HechoInputDTO>> getHechos()
  }

  interface ServidoraDeHechosPorId extends ServidoraDeHechos {
    +Mono<HechoInputDTO> getHechoPorId(Long id)
  }

  interface ServidoraDeHechosConFiltros extends ServidoraDeHechos {
    +Mono<List<HechoInputDTO>> buscarHechos(HechosFilterDTO filtros)
  }

  interface ServidoraDeEliminaciones extends IFuente {
    +Mono<Void> crearSolicitudEliminacion(SolicitudEliminarHechoOutputDTO solicitud)
  }

  interface ServidoraDeColecciones extends IFuente {
    +Mono<List<ColeccionInputDTO>> buscarTodasLasColecciones()
    +Mono<List<HechoInputDTO>> buscarHechosPorColeccion(String handle, Boolean curado, HechosFilterDTO filtros)
  }

  ' ===== Clase base (abstracta) =====
  abstract class Fuente {
    #Long id
    #String nombre
    #String baseUrl
    #boolean habilitada
  }

  ' ===== Implementaciones ====
