@startuml
' Diagrama UML para el modelo de hechos y criterios

class Hecho {
    - id: Long
    - origenId: Long
    - fuente: IFuente
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - ubicacion: Ubicacion
    - fechaDeOcurrencia: LocalDate
    - fechaDeCarga: LocalDateTime
    - contenidoMultimedia: IContenidoMultimedia
    - fueEliminado: Boolean
    - tipoHecho: TipoHecho
    - contribuyente : Contribuyente
}

enum TipoHecho {
    ESTATICO,
    DINAMICO,
    PROXY
}

interface IFuente {}

class FuenteDinamica{
    - id: Long
    - url: String
    - nombre: String
    - tipo : TipoFuente
    - webClient: WebClient
    + getHechos(): List<HechoDTO>
}

class FuenteEstatica{
    - id: Long
    - url: String
    - nombre: String
    - tipo : TipoFuente
    - webClient: WebClient
    + getHechos(): List<HechoDTO>
}

class FuenteProxy{
    - id: Long
    - url: String
    - nombre: String
    - tipo : TipoFuente
    - webClient: WebClient
    + getHechos(): List<HechoDTO>
}

enum TipoFuente{
    ESTATICA,
    DINAMICA,
    PROXY
}

class Coleccion{
    - handle: String
    - titulo: String
    - descripcion: String
    - listaFuentes: List<IFuentes>
    - listaCriterios: Set<ICriterio>
    - algoritmoConsenso: IAlgoritmoConsenso
    - listaHechos: List<Hecho>
    - listaHechosCurados: List<Hecho>
    - actualizarHechos: Boolean
    - curarHechos: Boolean
    + filtrarHechos(List<Hecho>): List<Hecho>
    + actualizarHechos():void
    + curarHechos():void
    + getHechos(): List<Hecho>
    + getHechosCurados(): List<Hecho>
    + getHechosConFiltro(List<ICriterio>): List<Hecho>
    + getHechosCuradosYFiltrados(List<ICriterio>=: List<Hecho>
}

class Categoria{
    - id: String
    - nombre: String
}

class EquivalenteCategoria{
    - id: Long
    - equivalente: String
    - categoria: Categoria
}

class Contribuyente {
    - id: Long
    - nombre: String
    - apellido: String
    - fechaNacimiento: LocalDate
    - esAnonimo: Boolean
    + getNombreDisplay(): String
}

class Ubicacion {
    - id: Long
    - provincia: String
    - localidad: String
    - calle: String
    - numero: Integer
    - latitud: Double
    - longitud:Double
}

interface IContenidoMultimedia{
    + getURL(): String
}

interface ICriterio{
    + pertenece(Hecho): Boolean
}

interface IAlgoritmoConsenso {
    + getTipo(): TipoAlgoritmoConsenso
    + curar(List<Hecho>, List<IFuente>): List<Hecho>
}

enum TipoAlgoritmoConsenso {
    ABSOLUTO,
    MAYORIASIMPLE,
    MULTIPLEMENCION
}

class ConcensoAbsoluto {
    + curar(List<Hecho>, List<IFuente>): List<Hecho>
}

class ConsensoMayoriaSimple {
    + curar(List<Hecho>, List<IFuente>): List<Hecho>
}

class ConsensoMultipleMencion {
    + curar(List<Hecho>, List<IFuente>): List<Hecho>
}

class SolicitudEliminarHecho {
    - id: Long
    - razonDeEliminacion: String
    - hecho: Hecho
    - estado: EstadoDeSolicitud
    - nombreCreador: String
    - apellidoCreador: String
    - nombreAdministrador: String
    - apellidoAdministrador: String
    - fechaCreacion: LocalDateTime
    - fechaGestion: LocalDateTime
    - eliminada: Boolean
    - actualizarFuenteOrigen: Boolean
    + serAceptada(String nombreAdministrador, String apellidoAdministrador): void
    + serRechazada(String nombreAdministrador, String apellidoAdministrador): void
}

enum EstadoDeSolicitud {
    ACEPTADA,
    RECHAZADA,
    PENDIENTE,
    SPAM
}

class ConstructorSolicitudesEliminacion {
    + constructorSolicitud (Hecho hecho, String razonDeEliminacion, String nombreContribuyente, String apellidoContribuyente): SolicitudEliminarHecho
}

class HechoFilter {
    - categoria: String
    - fReporteDesde: LocalDateTime
    - fReporteHasta: LocalDateTime
    - fAconDesde:LocalDate
    - fAconHasta: LocalDate
    - ubicacion: Ubicacion
}

interface IComandComparator {
    + comparar(Hecho hecho1, Hecho hecho2): Boolean
}
class HechoComparator{
    - listaComandos: List<IComandComparator>
    + agregarComando(IComandComparator comando): void
    + eliminarComando(IComandComparator comando): void
    + compararHechos(Hecho h1, Hecho h2): Boolean
}
class CompararUbicacion{
    + comparar(Hecho hecho1, Hecho hecho2): Boolean
}
class CompararTitulo{
    + comparar(Hecho hecho1, Hecho hecho2): Boolean
    - normalizarTitulo(String titulo): String
}
class COmpararFechaDeOcurrencia{
    + comparar(Hecho hecho1, Hecho hecho2): Boolean
}
class CompararDescripcion{
    + comparar(Hecho hecho1, Hecho hecho2): Boolean
    - normalizarDescripcion(String descripcion): String
}
class CompararCategoria{
    + comparar(Hecho hecho1, Hecho hecho2): Boolean
}

interface IDetectorDeSpam{
    + esSpam(String texto): Boolean
}
class DetectorDeSpam{
    + esSpam(String texto): Boolean


    private String stringToHandle(String string) {



    private boolean contienePalabrasSpam(String texto) {


        private boolean contienePalabrasRepetidas(String texto) {

        private boolean contieneExcesoDeSignos(String texto) {

        private boolean esMayormenteMayusculas(String texto) {


        private boolean contieneMuchasUrls(String texto) {

        private boolean contieneMuchosCaracteresNoAlfabeticos(String texto)
}

class NormalizadorTexto{}
class NormalizadorUbicacion

class Georef{
-webClient : WebClient
+geolocalizar(Ubicacion ubi): Ubicacion
+obtenerDireccion(Ubicacion ubicacion): Ubicacion
+obtenerCoordenadas(Ubicacion ubicacion): Ubicacion
}
interface IGeoLocalizador


Hecho -> TipoHecho
Hecho -> IFuente
Hecho -> Categoria
Hecho -> Contribuyente
Hecho -> IContenidoMultimedia
Hecho -> Ubicacion

IFuente <|.. FuenteDinamica
IFuente <|.. FuenteEstatica
IFuente <|.. FuenteProxy

FuenteDinamica -> TipoFuente
FuenteEstatica -> TipoFuente
FuenteProxy -> TipoFuente

Coleccion -* Hecho
Coleccion -* IFuente
Coleccion -* ICriterio
Coleccion -> IAlgoritmoConsenso

IAlgoritmoConsenso -> TipoAlgoritmoConsenso

HechoFilter -> Ubicacion

IComandComparator <|.. HechoComparator
IComandComparator <|.. CompararCategoria
IComandComparator <|.. CompararDescripcion
IComandComparator <|.. COmpararFechaDeOcurrencia
IComandComparator <|.. CompararTitulo
IComandComparator <|.. CompararUbicacion

IAlgoritmoConsenso <|.. ConcensoAbsoluto
IAlgoritmoConsenso <|.. ConsensoMayoriaSimple
IAlgoritmoConsenso <|.. ConsensoMultipleMencion

IGeoLocalizador <|.. Georef



SolicitudEliminarHecho -> EstadoDeSolicitud
SolicitudEliminarHecho -> Hecho
ConstructorSolicitudesEliminacion -> SolicitudEliminarHecho

@enduml
