spring.application.name=fuenteProxy
server.port=${SERVER_PORT}

# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD según las entidades (muy usado en desarrollo).
# create: crea las tablas en cada inicio.
# create-drop: igual que create pero borra al apagar.
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#FUENTE DDS
api.ddsi.base-url=https://api-ddsi.disilab.ar/public
api.ddsi.token=${DDSI_TOKEN}

#FUENTE METAMAPA
api.metamapa.base-url=https://22e8acb1-7e59-4c25-94fb-d9892865200e.mock.pstmn.io
spring.profiles.active=dev


#SCHEDULER
hechos.sync.cron=0 */30 * * * *
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.mvc.async.request-timeout=200s

# Configuración JWT (validador)
jwt.secret.base64= ${JWT_SECRET_BASE64}
