spring.application.name=fuenteProxy
server.port=${SERVER_PORT}

# Configuración de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de sincronización de entities contra la base de datos
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
# none: no toca la BD.
# validate: valida que las entidades coincidan con la BD.
# update: actualiza la BD según las entidades (muy usado en desarrollo).
# create: crea las tablas en cada inicio.
# create-drop: igual que create pero borra al apagar.
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#FUENTE DDS
api.ddsi.base-url=https://api-ddsi.disilab.ar/public
api.ddsi.token=${DDSI_TOKEN}


spring.profiles.active=dev


#SCHEDULER
hechos.sync.cron=0 */30 * * * *
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.mvc.async.request-timeout=200s

# Configuración JWT (validador)
jwt.secret.base64= ${JWT_SECRET_BASE64}

# Configuración Datadog

## Exponer endpoints de Actuator (para health y metrics)
management.endpoints.web.exposure.include=health,info,metrics

# API key de Datadog (inyectada por env var)
management.datadog.metrics.export.api-key=${DD_API_KEY}

# Site de Datadog (porque estás en us3)
management.datadog.metrics.export.uri=https://api.us3.datadoghq.com

# Enviar métricas cada 10s
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.step=10s

# Tags globales para todas las métricas
management.metrics.tags.env=${DD_ENV}
management.metrics.tags.service=${spring.application.name}
management.metrics.tags.version=${DD_VERSION}

