// js/hechos.js
const HECHOS = [
  {
    id: 1,
    title: "Robo en Recoleta",
    description: "Un robo a mano armada ocurrió en una joyería de Recoleta. Los delincuentes escaparon en moto y la policía investiga el hecho.",
    ubicacion: "Recoleta, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Robo",
    fecha: "2023-05-12",
    img: "",
    lat: -34.5875,
    lng: -58.3932
  },
  {
    id: 2,
    title: "Accidente de tránsito en Córdoba",
    description: "Un choque múltiple en la Avenida Circunvalación dejó tres heridos y generó demoras en el tránsito.",
    ubicacion: "Córdoba",
    categoria: "Accidente",
    etiqueta: "Tránsito",
    fecha: "2024-01-18",
    img: "",
    lat: -31.4201,
    lng: -64.1888
  },
  {
    id: 3,
    title: "Incendio en Rosario",
    description: "Un incendio en un edificio céntrico fue controlado por bomberos. No hubo víctimas fatales.",
    ubicacion: "Rosario, Santa Fe",
    categoria: "Accidente",
    etiqueta: "Incendio",
    fecha: "2023-11-03",
    img: "",
    lat: -32.9468,
    lng: -60.6393
  },
  {
    id: 4,
    title: "Allanamiento en La Plata",
    description: "La policía realizó un allanamiento en una vivienda sospechada de venta de drogas. Se incautaron estupefacientes.",
    ubicacion: "La Plata, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Allanamiento",
    fecha: "2024-03-22",
    img: "",
    lat: -34.9214,
    lng: -57.9545
  },
  {
    id: 5,
    title: "Secuestro en San Miguel",
    description: "Una persona fue secuestrada y liberada tras el pago de rescate. Hay dos detenidos.",
    ubicacion: "San Miguel, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Secuestro",
    fecha: "2023-09-14",
    img: "",
    lat: -34.5433,
    lng: -58.7156
  },
  {
    id: 6,
    title: "Vuelco de colectivo en Mendoza",
    description: "Un colectivo volcó en la Ruta 7. Hay varios heridos, algunos de gravedad.",
    ubicacion: "Mendoza",
    categoria: "Accidente",
    etiqueta: "Vuelco",
    fecha: "2024-02-10",
    img: "",
    lat: -32.8895,
    lng: -68.8458
  },
  {
    id: 7,
    title: "Asalto a mano armada en Mar del Plata",
    description: "Un comercio fue asaltado por dos individuos armados. No hubo heridos.",
    ubicacion: "Mar del Plata, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Asalto",
    fecha: "2023-07-28",
    img: "",
    lat: -38.0055,
    lng: -57.5426
  },
  {
    id: 8,
    title: "Desaparición en Tucumán",
    description: "Una joven desapareció en San Miguel de Tucumán. Se activó el protocolo de búsqueda.",
    ubicacion: "San Miguel de Tucumán, Tucumán",
    categoria: "Policial",
    etiqueta: "Desaparición",
    fecha: "2024-04-05",
    img: "",
    lat: -26.8241,
    lng: -65.2226
  },
  {
    id: 9,
    title: "Choque de trenes en Retiro",
    description: "Dos trenes colisionaron en la estación Retiro. Hay varios pasajeros con lesiones leves.",
    ubicacion: "Retiro, Buenos Aires",
    categoria: "Accidente",
    etiqueta: "Choque",
    fecha: "2023-12-19",
    img: "",
    lat: -34.5922,
    lng: -58.3700
  },
  {
    id: 10,
    title: "Estafa virtual en Bahía Blanca",
    description: "Una banda fue desbaratada tras realizar estafas virtuales a vecinos de Bahía Blanca.",
    ubicacion: "Bahía Blanca, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Estafa",
    fecha: "2024-05-01",
    img: "",
    lat: -38.7196,
    lng: -62.2655
  },
  {
    id: 11,
    title: "Fuga de presos en Salta",
    description: "Tres presos se fugaron de una comisaría en Salta. La policía montó un operativo de búsqueda.",
    ubicacion: "Salta",
    categoria: "Policial",
    etiqueta: "Fuga",
    fecha: "2023-08-16",
    img: "",
    lat: -24.7821,
    lng: -65.4232
  },
  {
    id: 12,
    title: "Accidente náutico en Tigre",
    description: "Una lancha chocó contra un muelle en Tigre. Dos personas resultaron heridas.",
    ubicacion: "Tigre, Buenos Aires",
    categoria: "Accidente",
    etiqueta: "Náutico",
    fecha: "2024-03-30",
    img: "",
    lat: -34.4264,
    lng: -58.5796
  },
  {
    id: 13,
    title: "Violento tiroteo en Quilmes",
    description: "Un tiroteo entre bandas dejó un herido grave en Quilmes.",
    ubicacion: "Quilmes, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Tiroteo",
    fecha: "2023-10-21",
    img: "",
    lat: -34.7207,
    lng: -58.2546
  },
  {
    id: 14,
    title: "Incendio forestal en Bariloche",
    description: "Un incendio forestal afectó varias hectáreas cerca de Bariloche. Bomberos trabajan en la zona.",
    ubicacion: "Bariloche, Río Negro",
    categoria: "Accidente",
    etiqueta: "Incendio",
    fecha: "2024-01-07",
    img: "",
    lat: -41.1335,
    lng: -71.3103
  },
  {
    id: 15,
    title: "Secuestro exprés en San Isidro",
    description: "Una familia fue víctima de un secuestro exprés en San Isidro. Los delincuentes fueron detenidos.",
    ubicacion: "San Isidro, Buenos Aires",
    categoria: "Policial",
    etiqueta: "Secuestro",
    fecha: "2023-06-11",
    img: "",
    lat: -34.4732,
    lng: -58.5276
  }
];
window.HECHOS = HECHOS;