const HECHOS = [
  {
    id: 1,
    title: "Incendio forestal en Córdoba",
    description: "El 15 de septiembre de 2023, un incendio forestal de gran magnitud se desató en las sierras de Córdoba, afectando más de 2.000 hectáreas de vegetación autóctona. El fuego, avivado por fuertes vientos y altas temperaturas, obligó a evacuar a varias familias y movilizó a bomberos de toda la provincia. Las tareas de extinción se extendieron durante varios días y requirieron el uso de aviones hidrantes y maquinaria pesada. El siniestro provocó importantes daños ecológicos y puso en riesgo la fauna local.",
    ubicacion: "Sierras de Córdoba",
    categoria: "Incendio Forestal",
    etiqueta: "Emergencia",
    fecha: "15 septiembre 2023",
    img: "images/incendio_cordoba.jpg",
    lat: -31.4201,
    lng: -64.1888,
    fuente: "Ministerio de Seguridad Córdoba"
  },
  {
    id: 2,
    title: "Robo a mano armada en Rosario",
    description: "El 22 de agosto de 2023, una banda armada ingresó a una joyería ubicada en el centro de Rosario y sustrajo objetos de valor por un monto estimado en varios millones de pesos. El hecho ocurrió en horas de la tarde y generó pánico entre los empleados y clientes presentes. Los delincuentes lograron huir antes de la llegada de la policía, que inició una investigación y desplegó operativos en la zona. El robo fue registrado por cámaras de seguridad y se encuentra bajo investigación judicial.",
    ubicacion: "Rosario",
    categoria: "Robo",
    etiqueta: "Delito",
    fecha: "22 agosto 2023",
    img: "images/robo_rosario.jpg",
    lat: -32.9468,
    lng: -60.6393,
    fuente: "Policía de Santa Fe"
  },
  {
    id: 3,
    title: "Incendio en edificio de Buenos Aires",
    description: "El 10 de octubre de 2023, un incendio se produjo en el sexto piso de un edificio residencial en el barrio de Palermo, Buenos Aires. El fuego se inició por un cortocircuito en una estufa eléctrica y se propagó rápidamente, obligando a evacuar a los vecinos. Bomberos de la Ciudad lograron controlar el siniestro tras varias horas de trabajo. No se registraron víctimas fatales, pero sí daños materiales importantes y algunos heridos leves por inhalación de humo.",
    ubicacion: "Palermo, Buenos Aires",
    categoria: "Incendio",
    etiqueta: "Emergencia",
    fecha: "10 octubre 2023",
    img: "images/incendio_palermo.jpg",
    lat: -34.5836,
    lng: -58.4255,
    fuente: "Bomberos de la Ciudad"
  },
  {
    id: 4,
    title: "Desalojo por toma de terrenos en Merlo",
    description: "El 5 de noviembre de 2023, fuerzas policiales realizaron un operativo de desalojo en un predio ocupado ilegalmente en el partido de Merlo, provincia de Buenos Aires. El procedimiento se llevó a cabo tras una orden judicial y contó con la presencia de personal de Infantería y ambulancias. Los ocupantes fueron retirados pacíficamente, aunque se registraron algunos incidentes menores. El predio será destinado a la construcción de viviendas sociales.",
    ubicacion: "Merlo, Buenos Aires",
    categoria: "Desalojo",
    etiqueta: "Judicial",
    fecha: "05 noviembre 2023",
    img: "images/desalojo_merlo.jpg",
    lat: -34.6654,
    lng: -58.7276,
    fuente: "Municipalidad de Merlo"
  },
  {
    id: 5,
    title: "Accidente vial en Ruta 9",
    description: "El 18 de julio de 2023, un choque múltiple ocurrió en la Ruta Nacional 9 a la altura de San Nicolás, involucrando a cinco vehículos. El accidente se produjo en condiciones de niebla intensa y dejó como saldo tres personas heridas, una de ellas de gravedad. Personal de emergencias médicas y bomberos trabajaron en el lugar para asistir a los afectados y liberar la calzada. El tránsito estuvo interrumpido durante varias horas.",
    ubicacion: "San Nicolás, Buenos Aires",
    categoria: "Accidente Vial",
    etiqueta: "Tránsito",
    fecha: "18 julio 2023",
    img: "images/accidente_ruta9.jpg",
    lat: -33.3292,
    lng: -60.2209,
    fuente: "Agencia Nacional de Seguridad Vial"
  },
  {
    id: 6,
    title: "Incendio en fábrica textil de Lanús",
    description: "El 2 de diciembre de 2023, un incendio de grandes proporciones afectó una fábrica textil ubicada en Lanús Oeste. El fuego se inició en el sector de depósitos y se expandió rápidamente debido a la presencia de materiales inflamables. Bomberos voluntarios de la zona trabajaron durante más de seis horas para controlar el siniestro. No hubo víctimas fatales, pero sí importantes pérdidas materiales y evacuación preventiva de viviendas cercanas.",
    ubicacion: "Lanús, Buenos Aires",
    categoria: "Incendio Industrial",
    etiqueta: "Emergencia",
    fecha: "02 diciembre 2023",
    img: "images/incendio_lanus.jpg",
    lat: -34.7063,
    lng: -58.3921,
    fuente: "Bomberos Voluntarios Lanús"
  },
  {
    id: 7,
    title: "Robo de vehículos en Mendoza",
    description: "El 27 de septiembre de 2023, una banda delictiva robó tres automóviles de alta gama en distintos barrios de la ciudad de Mendoza. Los hechos ocurrieron durante la madrugada y fueron denunciados por los propietarios al notar la ausencia de sus vehículos. La policía local inició una investigación y logró recuperar uno de los autos tras una persecución. El caso continúa bajo investigación y se sospecha de una red organizada.",
    ubicacion: "Mendoza",
    categoria: "Robo",
    etiqueta: "Automotor",
    fecha: "27 septiembre 2023",
    img: "images/robo_mendoza.jpg",
    lat: -32.8908,
    lng: -68.8272,
    fuente: "Ministerio de Seguridad Mendoza"
  },
  {
    id: 8,
    title: "Incendio forestal en Bariloche",
    description: "El 8 de enero de 2024, un incendio forestal se desató en la zona de Llao Llao, Bariloche, afectando bosques nativos y poniendo en riesgo viviendas cercanas. El fuego se propagó rápidamente debido a las altas temperaturas y la sequía. Brigadistas, bomberos y voluntarios trabajaron intensamente para contener el avance de las llamas. El siniestro generó preocupación por el impacto ambiental y la pérdida de biodiversidad.",
    ubicacion: "Bariloche, Río Negro",
    categoria: "Incendio Forestal",
    etiqueta: "Emergencia",
    fecha: "08 enero 2024",
    img: "images/incendio_bariloche.jpg",
    lat: -41.1335,
    lng: -71.3103,
    fuente: "Parques Nacionales"
  },
  {
    id: 9,
    title: "Allanamiento por narcotráfico en Salta",
    description: "El 14 de febrero de 2024, la Gendarmería Nacional realizó un allanamiento en una vivienda de la ciudad de Salta, donde se incautaron más de 50 kilos de marihuana y cocaína. El operativo fue resultado de una investigación de varios meses y permitió la detención de tres personas vinculadas a una red de tráfico de drogas. Los detenidos fueron puestos a disposición de la justicia federal.",
    ubicacion: "Salta",
    categoria: "Narcotráfico",
    etiqueta: "Operativo",
    fecha: "14 febrero 2024",
    img: "images/allanamiento_salta.jpg",
    lat: -24.7821,
    lng: -65.4232,
    fuente: "Gendarmería Nacional"
  },
  {
    id: 10,
    title: "Incendio en hospital de La Plata",
    description: "El 20 de marzo de 2024, un incendio se produjo en el sector de pediatría del Hospital San Martín de La Plata. El fuego se originó por un desperfecto eléctrico y obligó a evacuar a pacientes y personal médico. Bomberos lograron controlar el siniestro en menos de una hora, evitando daños mayores. No se registraron heridos, pero sí daños materiales en el área afectada.",
    ubicacion: "La Plata, Buenos Aires",
    categoria: "Incendio",
    etiqueta: "Salud",
    fecha: "20 marzo 2024",
    img: "images/incendio_laplata.jpg",
    lat: -34.9214,
    lng: -57.9545,
    fuente: "Ministerio de Salud Buenos Aires"
  },
  {
    id: 11,
    title: "Robo en supermercado de Mar del Plata",
    description: "El 3 de abril de 2024, un grupo de delincuentes ingresó a un supermercado en el barrio Constitución de Mar del Plata y sustrajo dinero en efectivo y mercadería. El hecho ocurrió durante la madrugada y fue detectado por el sistema de alarmas. La policía realizó un operativo en la zona y logró detener a uno de los sospechosos. El caso está siendo investigado por la fiscalía local.",
    ubicacion: "Mar del Plata, Buenos Aires",
    categoria: "Robo",
    etiqueta: "Comercial",
    fecha: "03 abril 2024",
    img: "images/robo_mardelplata.jpg",
    lat: -38.0055,
    lng: -57.5426,
    fuente: "Policía Bonaerense"
  },
  {
    id: 12,
    title: "Incendio en depósito de San Juan",
    description: "El 12 de mayo de 2024, un incendio afectó un depósito de materiales de construcción en la ciudad de San Juan. El fuego se inició por la combustión de solventes y pinturas almacenadas y se expandió rápidamente. Bomberos voluntarios lograron controlar el siniestro tras varias horas de trabajo. No hubo víctimas, pero sí importantes pérdidas materiales.",
    ubicacion: "San Juan",
    categoria: "Incendio Industrial",
    etiqueta: "Emergencia",
    fecha: "12 mayo 2024",
    img: "images/incendio_sanjuan.jpg",
    lat: -31.5375,
    lng: -68.5364,
    fuente: "Bomberos Voluntarios San Juan"
  },
  {
    id: 13,
    title: "Accidente ferroviario en Retiro",
    description: "El 28 de junio de 2024, una formación del tren Mitre descarriló al ingresar a la estación Retiro, en la Ciudad de Buenos Aires. El accidente se produjo por una falla en el sistema de señales y dejó como saldo cinco personas heridas, ninguna de gravedad. Personal de emergencias y bomberos asistieron a los pasajeros y trabajaron en la remoción de los vagones afectados. El servicio estuvo interrumpido durante varias horas.",
    ubicacion: "Retiro, Buenos Aires",
    categoria: "Accidente Ferroviario",
    etiqueta: "Transporte",
    fecha: "28 junio 2024",
    img: "images/accidente_retiro.jpg",
    lat: -34.5922,
    lng: -58.3707,
    fuente: "Trenes Argentinos"
  },
  {
    id: 14,
    title: "Incendio forestal en Misiones",
    description: "El 7 de febrero de 2024, un incendio forestal se desató en la reserva de la Biosfera Yabotí, provincia de Misiones. El fuego afectó más de 1.500 hectáreas de selva y requirió la intervención de brigadistas, bomberos y voluntarios. Las tareas de extinción se dificultaron por el difícil acceso y las altas temperaturas. El siniestro generó preocupación por el impacto ambiental y la pérdida de especies nativas.",
    ubicacion: "Yabotí, Misiones",
    categoria: "Incendio Forestal",
    etiqueta: "Emergencia",
    fecha: "07 febrero 2024",
    img: "images/incendio_misiones.jpg",
    lat: -27.2616,
    lng: -54.2194,
    fuente: "Ministerio de Ecología Misiones"
  },
  {
    id: 15,
    title: "Robo en banco de Tucumán",
    description: "El 19 de marzo de 2024, un grupo armado ingresó a una sucursal bancaria en San Miguel de Tucumán y sustrajo dinero en efectivo tras reducir al personal de seguridad. El hecho ocurrió en horas de la mañana y generó alarma entre los clientes presentes. La policía desplegó un operativo en la zona y logró recuperar parte del botín. El caso está siendo investigado por la justicia provincial.",
    ubicacion: "San Miguel de Tucumán",
    categoria: "Robo",
    etiqueta: "Bancario",
    fecha: "19 marzo 2024",
    img: "images/robo_tucuman.jpg",
    lat: -26.8241,
    lng: -65.2226,
    fuente: "Policía de Tucumán"
  },
  {
    id: 16,
    title: "Incendio en escuela de Neuquén",
    description: "El 25 de abril de 2024, un incendio se produjo en la Escuela N° 123 de la ciudad de Neuquén. El fuego se inició en el sector de cocina y se propagó a varias aulas. Bomberos lograron controlar el siniestro y evacuaron a los alumnos y docentes sin que se registraran heridos. El hecho generó preocupación entre la comunidad educativa y se investigan las causas del incendio.",
    ubicacion: "Neuquén",
    categoria: "Incendio",
    etiqueta: "Educativo",
    fecha: "25 abril 2024",
    img: "images/incendio_escuela_neuquen.jpg",
    lat: -38.9516,
    lng: -68.0591,
    fuente: "Ministerio de Educación Neuquén"
  },
  {
    id: 17,
    title: "Robo en estación de servicio de Formosa",
    description: "El 30 de mayo de 2024, dos delincuentes armados asaltaron una estación de servicio en la ciudad de Formosa, llevándose dinero en efectivo y pertenencias de los empleados. El hecho ocurrió durante la madrugada y fue registrado por cámaras de seguridad. La policía inició una investigación y busca a los responsables, que se dieron a la fuga en motocicleta.",
    ubicacion: "Formosa",
    categoria: "Robo",
    etiqueta: "Comercial",
    fecha: "30 mayo 2024",
    img: "images/robo_formosa.jpg",
    lat: -26.1775,
    lng: -58.1781,
    fuente: "Policía de Formosa"
  },
  {
    id: 18,
    title: "Incendio en galpón de Santa Fe",
    description: "El 11 de junio de 2024, un incendio afectó un galpón de almacenamiento de productos agrícolas en la ciudad de Santa Fe. El fuego se inició por la combustión de fertilizantes y se expandió rápidamente. Bomberos voluntarios lograron controlar el siniestro tras varias horas de trabajo. No hubo víctimas, pero sí importantes pérdidas materiales.",
    ubicacion: "Santa Fe",
    categoria: "Incendio Industrial",
    etiqueta: "Emergencia",
    fecha: "11 junio 2024",
    img: "images/incendio_santafe.jpg",
    lat: -31.6333,
    lng: -60.7000,
    fuente: "Bomberos Voluntarios Santa Fe"
  },
  {
    id: 19,
    title: "Accidente vial en Córdoba capital",
    description: "El 6 de julio de 2024, un choque entre un colectivo y un automóvil ocurrió en la avenida Circunvalación de Córdoba capital. El accidente se produjo en horas de la mañana y dejó como saldo dos personas heridas, una de ellas de gravedad. Personal de emergencias médicas y bomberos asistieron a los afectados y liberaron la calzada. El tránsito estuvo interrumpido durante varias horas.",
    ubicacion: "Córdoba",
    categoria: "Accidente Vial",
    etiqueta: "Tránsito",
    fecha: "06 julio 2024",
    img: "images/accidente_cordoba.jpg",
    lat: -31.4167,
    lng: -64.1833,
    fuente: "Policía de Córdoba"
  },
  {
    id: 20,
    title: "Incendio forestal en San Luis",
    description: "El 17 de enero de 2024, un incendio forestal se desató en la zona de las Sierras de los Comechingones, San Luis. El fuego afectó más de 800 hectáreas de pastizales y bosques nativos. Brigadistas y bomberos trabajaron intensamente para contener el avance de las llamas. El siniestro generó preocupación por el impacto ambiental y la pérdida de biodiversidad.",
    ubicacion: "Sierras de los Comechingones, San Luis",
    categoria: "Incendio Forestal",
    etiqueta: "Emergencia",
    fecha: "17 enero 2024",
    img: "images/incendio_sanluis.jpg",
    lat: -32.2167,
    lng: -65.0167,
    fuente: "Ministerio de Medio Ambiente San Luis"
  },
  {
    id: 21,
    title: "Robo en comercio de Chaco",
    description: "El 21 de junio de 2024, un grupo de delincuentes ingresó a un local de electrodomésticos en Resistencia, Chaco, y sustrajo productos de alto valor. El hecho ocurrió durante la noche y fue detectado por el sistema de alarmas. La policía realizó un operativo en la zona y logró detener a uno de los sospechosos. El caso está siendo investigado por la fiscalía local.",
    ubicacion: "Resistencia, Chaco",
    categoria: "Robo",
    etiqueta: "Comercial",
    fecha: "21 junio 2024",
    img: "images/robo_chaco.jpg",
    lat: -27.4516,
    lng: -58.9867,
    fuente: "Policía de Chaco"
  },
  {
    id: 22,
    title: "Incendio en hotel de Ushuaia",
    description: "El 3 de julio de 2024, un incendio se produjo en el segundo piso de un hotel céntrico en Ushuaia, Tierra del Fuego. El fuego se inició por un desperfecto eléctrico y obligó a evacuar a los huéspedes y personal. Bomberos lograron controlar el siniestro en menos de una hora, evitando daños mayores. No se registraron heridos, pero sí daños materiales en el área afectada.",
    ubicacion: "Ushuaia, Tierra del Fuego",
    categoria: "Incendio",
    etiqueta: "Turismo",
    fecha: "03 julio 2024",
    img: "images/incendio_ushuaia.jpg",
    lat: -54.8019,
    lng: -68.3030,
    fuente: "Bomberos Ushuaia"
  },
  {
    id: 23,
    title: "Accidente vial en Posadas",
    description: "El 15 de junio de 2024, un choque entre una motocicleta y un automóvil ocurrió en la avenida Uruguay de Posadas, Misiones. El accidente se produjo en horas de la tarde y dejó como saldo una persona herida de gravedad. Personal de emergencias médicas asistió al afectado y liberó la calzada. El tránsito estuvo interrumpido durante varias horas.",
    ubicacion: "Posadas, Misiones",
    categoria: "Accidente Vial",
    etiqueta: "Tránsito",
    fecha: "15 junio 2024",
    img: "images/accidente_posadas.jpg",
    lat: -27.3671,
    lng: -55.8961,
    fuente: "Policía de Misiones"
  },
  {
    id: 24,
    title: "Incendio forestal en Catamarca",
    description: "El 9 de febrero de 2024, un incendio forestal se desató en la zona de la Cuesta del Portezuelo, Catamarca. El fuego afectó más de 600 hectáreas de vegetación y requirió la intervención de brigadistas, bomberos y voluntarios. Las tareas de extinción se dificultaron por el difícil acceso y las altas temperaturas. El siniestro generó preocupación por el impacto ambiental y la pérdida de especies nativas.",
    ubicacion: "Cuesta del Portezuelo, Catamarca",
    categoria: "Incendio Forestal",
    etiqueta: "Emergencia",
    fecha: "09 febrero 2024",
    img: "images/incendio_catamarca.jpg",
    lat: -28.4696,
    lng: -65.7795,
    fuente: "Ministerio de Ambiente Catamarca"
  },
  {
    id: 25,
    title: "Robo en farmacia de Río Gallegos",
    description: "El 12 de julio de 2024, un grupo de delincuentes ingresó a una farmacia en el centro de Río Gallegos, Santa Cruz, y sustrajo dinero en efectivo y medicamentos. El hecho ocurrió durante la madrugada y fue detectado por el sistema de alarmas. La policía realizó un operativo en la zona y logró detener a uno de los sospechosos. El caso está siendo investigado por la fiscalía local.",
    ubicacion: "Río Gallegos, Santa Cruz",
    categoria: "Robo",
    etiqueta: "Comercial",
    fecha: "12 julio 2024",
    img: "images/robo_riogallegos.jpg",
    lat: -51.6230,
    lng: -69.2168,
    fuente: "Policía de Santa Cruz"
  },
  {
    id: 26,
    title: "Incendio en fábrica de alimentos en Bahía Blanca",
    description: "El 18 de junio de 2024, un incendio afectó una fábrica de alimentos en Bahía Blanca, provincia de Buenos Aires. El fuego se inició en el sector de producción y se expandió rápidamente debido a la presencia de materiales inflamables. Bomberos voluntarios lograron controlar el siniestro tras varias horas de trabajo. No hubo víctimas, pero sí importantes pérdidas materiales.",
    ubicacion: "Bahía Blanca, Buenos Aires",
    categoria: "Incendio Industrial",
    etiqueta: "Emergencia",
    fecha: "18 junio 2024",
    img: "images/incendio_bahiablanca.jpg",
    lat: -38.7183,
    lng: -62.2663,
    fuente: "Bomberos Voluntarios Bahía Blanca"
  },
  {
    id: 27,
    title: "Accidente vial en San Rafael",
    description: "El 22 de julio de 2024, un choque entre dos camiones ocurrió en la Ruta Nacional 143 a la altura de San Rafael, Mendoza. El accidente se produjo en horas de la madrugada y dejó como saldo una persona herida de gravedad. Personal de emergencias médicas asistió al afectado y liberó la calzada. El tránsito estuvo interrumpido durante varias horas.",
    ubicacion: "San Rafael, Mendoza",
    categoria: "Accidente Vial",
    etiqueta: "Tránsito",
    fecha: "22 julio 2024",
    img: "images/accidente_sanrafael.jpg",
    lat: -34.6177,
    lng: -68.3301,
    fuente: "Policía de Mendoza"
  },
  {
    id: 28,
    title: "Incendio forestal en El Bolsón",
    description: "El 5 de marzo de 2024, un incendio forestal se desató en la zona de Mallín Ahogado, El Bolsón, Río Negro. El fuego afectó más de 900 hectáreas de bosques y requirió la intervención de brigadistas, bomberos y voluntarios. Las tareas de extinción se dificultaron por el difícil acceso y las altas temperaturas. El siniestro generó preocupación por el impacto ambiental y la pérdida de especies nativas.",
    ubicacion: "El Bolsón, Río Negro",
    categoria: "Incendio Forestal",
    etiqueta: "Emergencia",
    fecha: "05 marzo 2024",
    img: "images/incendio_elbolson.jpg",
    lat: -41.9632,
    lng: -71.5333,
    fuente: "Ministerio de Ambiente Río Negro"
  },
  {
    id: 29,
    title: "Robo en comercio de San Luis",
    description: "El 8 de julio de 2024, un grupo de delincuentes ingresó a un local de indumentaria en el centro de San Luis y sustrajo productos de alto valor. El hecho ocurrió durante la noche y fue detectado por el sistema de alarmas. La policía realizó un operativo en la zona y logró detener a uno de los sospechosos. El caso está siendo investigado por la fiscalía local.",
    ubicacion: "San Luis",
    categoria: "Robo",
    etiqueta: "Comercial",
    fecha: "08 julio 2024",
    img: "images/robo_sanluis.jpg",
    lat: -33.2950,
    lng: -66.3356,
    fuente: "Policía de San Luis"
  },
  {
    id: 30,
    title: "Incendio en depósito de Corrientes",
    description: "El 16 de junio de 2024, un incendio afectó un depósito de materiales eléctricos en la ciudad de Corrientes. El fuego se inició por la combustión de cables y se expandió rápidamente. Bomberos voluntarios lograron controlar el siniestro tras varias horas de trabajo. No hubo víctimas, pero sí importantes pérdidas materiales.",
    ubicacion: "Corrientes",
    categoria: "Incendio Industrial",
    etiqueta: "Emergencia",
    fecha: "16 junio 2024",
    img: "images/incendio_corrientes.jpg",
    lat: -27.4692,
    lng: -58.8306,
    fuente: "Bomberos Voluntarios Corrientes"
  }
];
