@startuml
'https://plantuml.com/class-diagram

class Visualizador{
    - String nombre
    - String apellido
    - Integer edad

    + String consultarColeccion()
}

class Contribuyente extends Visualizador{
    + void consultarHecho()
    + void crearHecho()
    + void solicitudEliminar()
}

class Administrador extends Visualizador{
    + void revisarSolicitudEliminacion()
    + void revisarSolicitudEliminacionSpam()
    + void revisarHecho()
    + void etiquetarHecho(Hecho)
    + void crearColeccion()
}

class Hecho {
    - String titulo
    - String descripcion
    - Categoria categoria
    - localDateTime fecha
    - SoporteMultimedia soporteMultimedia
    - Double latitud
    - Double longitud
}

class SolicitudEliminacion{}

class Fuente{}

class Coleccion{
    - String titulo
    - String descripcion
    - CriterioPertenencia criterio
}

class Categoria{}
class CriterioPertenencia{}

class CriterioCargaEntreFechas extends CriterioPertenencia{}
class CriterioLugar extends CriterioPertenencia{}
class CriterioEvento extends CriterioPertenencia{}
class CriterioOcurrenciaEntreFechas extends CriterioPertenencia{}
class CriterioContenidoMultimedia extends CriterioPertenencia{}

Hecho --> Fuente
Hecho --> Categoria
Hecho --> Coleccion
Hecho --> Contribuyente

Visualizador --> Coleccion

Coleccion --> Fuente
Coleccion --> Hecho
Coleccion --> CriterioPertenencia

Coleccion --> Administrador

SolicitudEliminacion --> Hecho


@enduml